import os
import subprocess
import shutil

def compile_latex_to_pdf(tex_content: str, output_path: str) -> bool:
    """
    Takes raw LaTeX code generated by Qwen2.5-Coder, saves it to a .tex file, 
    and uses pdflatex (MiKTeX/TeX Live) to compile it into a strictly 1-page PDF.
    """
    
    # Ensure output directories exist
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    # Temporary files path
    base_name = os.path.splitext(output_path)[0]
    tex_path = f"{base_name}.tex"
    
    print(f"[TeX Compiler] Writing LaTeX source to {tex_path}")
    with open(tex_path, "w", encoding="utf-8") as f:
        f.write(tex_content)
        
    print("[TeX Compiler] Compiling PDF via pdflatex...")
    
    try:
        # Run pdflatex. -interaction=nonstopmode prevents it from halting on minor errors
        # -output-directory ensures the aux and log files go to the right place
        out_dir = os.path.dirname(output_path)
        filename = os.path.basename(tex_path)
        
        result = subprocess.run([
            "pdflatex", 
            "-interaction=nonstopmode", 
            f"-output-directory={out_dir}", 
            filename
        ], cwd=out_dir, check=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=60)
        
        # Clean up auxiliary files generated by LaTeX
        for ext in ['.aux', '.log', '.out']:
            aux_file = f"{base_name}{ext}"
            if os.path.exists(aux_file):
                os.remove(aux_file)
                
        if os.path.exists(output_path):
            print(f"[TeX Compiler] Successfully compiled 1-page PDF: {output_path}")
            return True
        else:
            print(f"[TeX Compiler] Failed to compile PDF. pdflatex output:\n{result.stdout.decode('utf-8', errors='ignore')}")
            return False
            
    except FileNotFoundError:
        print("[TeX Compiler Error] pdflatex not found! You must install MiKTeX (Windows) or TeX Live to compile LaTeX locally.")
        return False
    except Exception as e:
        print(f"[TeX Compiler Error] Compilation crashed: {e}")
        return False
